### ISSUE TITLE
Clarify support_iam_role_principal_arns

### ISSUE THREAD

**Issue by bcruik** [nozaq/terraform-aws-secure-baseline#179]
Hi,

Could you clarify what the support_iam_role_principal_arns should be?

Using say my SSO role `arn:aws:iam::65500000000:role/aws-reserved/sso.amazonaws.com/ap-southeast-2/AWSReservedSSO_AdministratorAccess_8123456789123c45` 

I get:
```
│ Error: Invalid value for input variable
│ 
│ The value entered for variable "support_iam_role_principal_arns" is not valid: list of any single type required.
```

**Comment by nozaq** [comment]
@bcruik 
I guess the problem is that `support_iam_role_principal_arns` expects a list of ARN strings, so you could pass one-element list instead of a single string.

If you're wondering what this variable does, please check  [CIS Amazon Web Services Foundations Benchmark](https://www.cisecurity.org/benchmark/amazon_web_services/) for the background of this requirement. In the latest version(1.4.0) of the benchmark, it's at ``1.17 Ensure a support role has been created to manage incidents with AWS Support`.
