### ISSUE TITLE
Default subnet not found for ca-central-1d

### ISSUE THREAD

**Issue by willfarrell** [nozaq/terraform-aws-secure-baseline#198]
If you run into this issue you need to create a new default subnet yourself. This a new AZ in Canada.
```
Error: Default subnet not found

  on .terraform/modules/security/modules/vpc-baseline/main.tf line 47, in resource "aws_default_subnet" "default":
  47: resource "aws_default_subnet" "default" {
 ```
 
 The following fixed it for me:
 ```bash
 # https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html#create-default-subnet
$ aws ec2 create-default-subnet --availability-zone ca-central-1d --region ca-central-1
 ```
 
No change required by this module. This can be left to auto-close.

**Comment by nozaq** [comment]
@willfarrell Thanks for the note!

Yes, this module throws an error when a default subnet does not exist in any of availability zones. This could happen when you deletes a default subnet manually, or a default subnet is not automatically created for newly added availability zones.
[AWS docs](https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html#default-vpc-components) says a default subnet wouldn't be created for new AZs when the default VPC is modified.

Currently this behavior can't be avoided since `aws_default_subnet` resource creation fails when no default subnet exists, and there's no way to check its existence in advance. 
After [this issue](https://github.com/hashicorp/terraform-provider-aws/issues/17540) in `terraform-provider-aws` is resolved, `aws_subnet_ids` could be used to detect the existence of a default subnet in each region. With this change, we could control the creation of `aws_default_subnet` depending on its return value.

It seems that this change would be included in the next major release of `terraform-provider-aws`, so I'll keep this ticket open until then.
