### ISSUE TITLE
how to use the providers block of different regions ?

### ISSUE THREAD

**Issue by shashipratap** [nozaq/terraform-aws-secure-baseline#223]
HI , 
in the main.tf of simple example you have given 
shouldnt we be using only one value here instead of all ?
by this you mean that it will benchmark in all regions ?

 providers = {
    aws                = aws
    aws.ap-northeast-1 = aws.ap-northeast-1
    aws.ap-northeast-2 = aws.ap-northeast-2
    aws.ap-northeast-3 = aws.ap-northeast-3
    aws.ap-south-1     = aws.ap-south-1
    aws.ap-southeast-1 = aws.ap-southeast-1
    aws.ap-southeast-2 = aws.ap-southeast-2
    aws.ca-central-1   = aws.ca-central-1
    aws.eu-central-1   = aws.eu-central-1
    aws.eu-north-1     = aws.eu-north-1
    aws.eu-west-1      = aws.eu-west-1
    aws.eu-west-2      = aws.eu-west-2
    aws.eu-west-3      = aws.eu-west-3
    aws.sa-east-1      = aws.sa-east-1
    aws.us-east-1      = aws.us-east-1
    aws.us-east-2      = aws.us-east-2
    aws.us-west-1      = aws.us-west-1
    aws.us-west-2      = aws.us-west-2
  }

**Comment by nozaq** [comment]
@shashipratap Yes, it's intentional. Hardening all regions, not only the ones you're actively using, would be required by security benchmarks such as [CIS benchmark](https://www.cisecurity.org/benchmark/amazon_web_services/) or [AWS foundational security best practices](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html).

**Comment by shashipratap** [comment]
so if i have to do it for a particular module there also i would need to specify all providers ex:-

module "alarm_baseline" {
  source = "nozaq/secure-baseline/aws//modules/alarm-baseline"

  cloudtrail_log_group_name = "cis-cloudtrail-loggroup"
providers = {
aws = aws
aws.ap-northeast-1 = aws.ap-northeast-1
aws.ap-northeast-2 = aws.ap-northeast-2
aws.ap-northeast-3 = aws.ap-northeast-3
aws.ap-south-1 = aws.ap-south-1
aws.ap-southeast-1 = aws.ap-southeast-1
aws.ap-southeast-2 = aws.ap-southeast-2
aws.ca-central-1 = aws.ca-central-1
aws.eu-central-1 = aws.eu-central-1
aws.eu-north-1 = aws.eu-north-1
aws.eu-west-1 = aws.eu-west-1
aws.eu-west-2 = aws.eu-west-2
aws.eu-west-3 = aws.eu-west-3
aws.sa-east-1 = aws.sa-east-1
aws.us-east-1 = aws.us-east-1
aws.us-east-2 = aws.us-east-2
aws.us-west-1 = aws.us-west-1
aws.us-west-2 = aws.us-west-2
}
}

**Comment by nozaq** [comment]
@shashipratap 
Only the root module (`secure-baseline` module itself) is designed to handle all regions. Submodules only create resources for one region at a time, so you need to call them for each region if you'd like to manage all regions. 
For example, [this file])(https://github.com/nozaq/terraform-aws-secure-baseline/blob/main/config_baselines.tf) calls `config-baseline` module for all regions.

That said, `alarm_baseline` module doesn't have to be called for each region if you set up CloudTrail as a multi-region trail so that the log records from all regions are published to one CloudWatch Logs log group.

**Comment by nozaq** [comment]
I close this issue as we haven't seen any update for few weeks.
Feel free to re-open if you have any comments or additional questions!
