### ISSUE TITLE
Move the modules to separate repositories

### ISSUE THREAD

**Issue by Cosaquee** [nozaq/terraform-aws-secure-baseline#28]
Hi! Excellent work putting all of this together!

Currently, the structure of the repository means that if someone wants to use anything they need to use everything or copy-paste the code into a separate module. Maybe you could create an organization and put modules into different repositories? This will allow using only what the person needs, and if it wants to use it all there still can be a repo that holds all of the modules.

**Comment by nozaq** [comment]
@Cosaquee Hi, thank you for the proposal! :)

If everything you need to do is to use some of submodules here, you can use them directly from Terraform Registry.

For example, instead of sourcing the root module, 

```hcl
module "secure-baseline" {
  source  = "nozaq/secure-baseline/aws"
  version = "0.6.0"

  # insert the 4 required variables here
}
```

you can source the submodule like this.
```hcl
module "secure-baseline_vpc-baseline" {
  source  = "nozaq/secure-baseline/aws//modules/vpc-baseline"
  version = "0.6.0"

  # insert the 2 required variables here
}
```

FYI: [Modules in Package Sub-directories](https://www.terraform.io/docs/modules/sources.html#modules-in-package-sub-directories).

Please let me know it is not enough for your use-case. I'm still happy to consider the repository organization 👍

**Comment by Cosaquee** [comment]
I did not know about the possibility of sourcing submodules, thank you! We can probably close this issue or wait for more feedback about organization idea :)

**Comment by nozaq** [comment]
@Cosaquee Sure, great to hear that!
