### ISSUE TITLE
Example links on https://registry.terraform.io/modules/nozaq/secure-baseline/aws/2.0.0 are dead

### ISSUE THREAD

**Issue by WTPascoe** [nozaq/terraform-aws-secure-baseline#298]
## Describe the bug

The example links within the text at https://registry.terraform.io/modules/nozaq/secure-baseline/aws/2.0.0 return 404 errors when clicking them:

* https://registry.terraform.io/modules/nozaq/secure-baseline/aws/examples/organization
* https://registry.terraform.io/modules/nozaq/secure-baseline/aws/examples/external-bucket
* https://registry.terraform.io/modules/nozaq/secure-baseline/aws/examples/simple/regions.tf

## Versions

- Terraform: N/A
- Provider: N/A
- Module: 2.0.0 and 1.1.0

## Reproduction

Visit any of the following links or click them from within the page at https://registry.terraform.io/modules/nozaq/secure-baseline/aws/2.0.0 

* https://registry.terraform.io/modules/nozaq/secure-baseline/aws/examples/organization
* https://registry.terraform.io/modules/nozaq/secure-baseline/aws/examples/external-bucket
* https://registry.terraform.io/modules/nozaq/secure-baseline/aws/examples/simple/regions.tf

## Expected behavior

Example documentation is returned

## Actual behavior

An error stating '404 Not Found' is returned in the browser

**Comment by nozaq** [comment]
@WTPascoe Thank you for reporting the issue. README.md contains relative links which were assumed be rendered on GitHub. Thus when rendered on Terraform Registry, these links were broken due to the wrong base URL.
I found that someone reported this issue in terraform registry, but still not resolved.
https://github.com/hashicorp/terraform/issues/21452

I will update README.md to use absolute links only in #300 .
