### ISSUE TITLE
Ability to use a central s3 bucket for audit logs when using a multi account organization

### ISSUE THREAD

**Issue by DevBOFH** [nozaq/terraform-aws-secure-baseline#47]
We could use an option to provide a bucket ARN instead of a name which would enable this module to have multiple accounts send audit logs to a single s3 bucket when in a multiple account organization.

**Comment by nozaq** [comment]
@DevBOFH 
Thanks for proposing! I agree allowing to use the centralized log bucket would be useful.
Working on it in #51, which should be released shortly :)

**Comment by nozaq** [comment]
Just released v0.14.0, which adds `use_external_audit_log_bucket` variable.
When it sets to true, the module use the bucket with the name equals to `audit_log_bucket_name` instead of creating a new bucket.

Please check [external-bucket](https://github.com/nozaq/terraform-aws-secure-baseline/tree/master/examples/external-bucket) example as well!

**Comment by DevBOFH** [comment]
Thanks @nozaq! I really appreciate it!
