### ISSUE TITLE
Suggestions: Make support_iam_role_principal_arn = optional

### ISSUE THREAD

**Issue by meabed** [nozaq/terraform-aws-secure-baseline#75]
Thank you! Great work.
While trying it out, I have another modules that manages my users/groups/iam policies etc... and in that case forcing to create user for support_iam_role_principal_arn doesn't fit really well as I will end up with 2 different modules managing users.

So it will be great if support_iam_role_principal_arn could be an optional feature.
What do you think? if so I could open a PR for it. 

Thanks :+1:

**Comment by nozaq** [comment]
@meabed 
I understand it's better to completely isolate user management from this module in some cases, happy to review a PR for this.
Thanks for your suggestion! :smiley:

**Comment by george-angel** [comment]
Since its being passed to `identifiers`, would it make sense for `support_iam_role_principal_arn` to become `support_iam_role_principal_arns` and be a list?

Then we satisfy the requirement of it being optional, and at the same time enable assigning multiple users to the support role.

Happy to PR if that sounds good.

**Comment by meabed** [comment]
Yes please :)
