### ISSUE TITLE
Error: Creating Delivery Channel failed: InsufficientDeliveryPolicyException: Insufficient delivery policy to s3 bucket

### ISSUE THREAD

**Issue by herigb** [nozaq/terraform-aws-secure-baseline#98]
I got the following error when I ran the secure baseline module as master defined in the account type attribute.

```
Error: Error creating CloudTrail: InsufficientS3BucketPolicyException: Incorrect S3 bucket policy is detected for bucket: audit-logs-XXXX3454-us-west-2

  on .terraform/modules/secure_baseline/terraform-aws-secure-baseline-0.17.0/modules/cloudtrail-baseline/main.tf line 223, in resource "aws_cloudtrail" "global":
 223: resource "aws_cloudtrail" "global" {

```
What I see in the output is that are trying to create the cloudtrail resource before creating the s3 bucket policy.

```
1 - Creating cloudtrail resource 
module.secure_baseline.module.cloudtrail_baseline.aws_cloudtrail.global[0]: Creating...
```

```
2 - Creating s3 bucket policy

module.secure_baseline.aws_s3_bucket_policy.audit_log[0]: Creating...

```

```
3 - Complete policy bucket

module.secure_baseline.aws_s3_bucket_policy.audit_log[0]: Creation comple
```

**Comment by nozaq** [comment]
@herigb Thanks for the report, and sorry for taking a while to respond!
The issue wasn't reproduced on my end, but it happens randomly because no dependency between the CloudTrail resource and the bucket policy resource.

I've created a PR( #102 ) to fix this, hopefully to push soon after some regression testing.
